Aqaint 194
etolmachev/OvernightPrintsSpec pull request #4
Opened 2018-01-22 12:28 UTC by DonkeyRit

2018-01-23 06:14 UTC, IgorRukhlenko requested changes

2018-01-23 06:14 UTC, IgorRukhlenko commented on OvernightPrintsSpecBindings/Bindings/BasketBindings.cs
> +		[When(@"I set (Discount Code|Shipping Zip Code) ""(.*)"" on the Basket Page")]
It's better to combine this step with the previous one and use table.
In this case you can use one step to specify all needed options on the Cart page.
And similar aproach can be used for verification of these values on the Cart page.

2018-01-23 06:14 UTC, IgorRukhlenko commented on OvernightPrintsSpecTests/FFs/Basket_Feature.feature
> +Scenario: Check Basket state when login user added item in the basket, logout, remove item from basket and login
Comment 'Let's check that such actions will effect on total price in the cart.' from Google Doc has not been fixed.

2018-01-23 06:14 UTC, IgorRukhlenko commented on OvernightPrintsSpecTests/FFs/Basket_Feature.feature
> +Scenario: Check Basket state after decline option "Professional File Review"
Comment ' I suggest you to check total price before and after declining of this option.' from Google Doc has not been fixed.

2018-01-23 06:14 UTC, IgorRukhlenko commented on OvernightPrintsSpecTests/FFs/Basket_Feature.feature
> +Scenario Template: Check Basket state after change product parameters on the basket
Comment 'Need to check total price before and after this action.' from Google Doc has not been fixed.

2018-01-23 06:14 UTC, IgorRukhlenko commented on OvernightPrintsSpecTests/FFs/Basket_Feature.feature
> +Scenario Template: Check Basket state after change shipping option
The same comment as for the previous scenarios. Need to check all prices on the Cart page before and after changes of some options.

2018-01-24 09:55 UTC, etolmachev requested changes

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/Bindings/BasketBindings.cs
> +			Assert.AreEqual(true,_basketPage.IsBasketPage());
Use Assert.True here

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/Bindings/BasketBindings.cs
> +			BasketPage page = new BasketPage();
Why we can't use _basketPage?

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/Bindings/BasketBindings.cs
> +				Assert.AreEqual(true, SearchItemBasket.GetAllItemsCart().Contains(new SearchItemBasket(row)));
Use Assert.True

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/Bindings/BasketBindings.cs
> +				Assert.AreEqual(false, SearchItemBasket.GetAllItemsCart().Contains(new SearchItemBasket(row)));
Assert.False

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/BasketPage.cs
> +			HtmlElement entity = new HtmlElement(By.XPath(_itemEntity.Replace("%s", productName)));
Instead of _itemEntity.Replace("%s", productName) use String.format.
for example:
string locator = "//div[contains(text(), '{0}')]";
string sometext = 'test';
var el = new HtmlElement(By.Xpath(String.format(locator, sometext)));

Please fix all places with this Replace thing

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/BasketPage.cs
> +					BasketPage page = new BasketPage();
No need to create BasketPage entity to Click. Instead of these two lines just use
Click("Remove");

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/BasketPage.cs
> +		public void WaitItemLoad(string productName, int timeout)
set some default value for timeout

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/BasketPage.cs
> +			HtmlElement htmlElement = new HtmlElement(entity.FindElement(By.ClassName("product-sku-choices")));
rename htmlElement to make code more readable

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/BasketPage.cs
> +			int t = timeout;
looks like you don't need 't' variable, you can just use timeout

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/BasketPage.cs
> +			while (t > 0 && !isExit)
Why we don't sleep every while iteration? In worse case this function works about several milliseconds, should be same number of seconds as set in timeout variable

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/BasketPage.cs
> +			Browser.WaitReadyState(timeout);
It's better to perform such things as separate common step. This hides logic and it's hard to predict whether your wait step has this inside or not.

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/Objects/SearchItemBasket.cs
> +	public class SearchItemBasket
Why SearchItemBasket? as I understand, you can call it just BasketItem

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/Objects/SearchItemBasket.cs
> +		public static List<SearchItemBasket> GetAllItemsCart()
This function/logic should be used in the Bindings part. This class only describes/creates/compares basket item.

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/Products/ApproveOrderPage.cs
> +			ProgressBar = new HtmlElement(_progressBarLocator);
Make it one line method

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/Products/BuilderPage.cs
> +			HtmlElement htmlElement;
Rename htmlElement, add more sense

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/Products/MailingListPage.cs
> +			SkipButton = new HtmlElement(_skipButtonLocator);
Make it one line method

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/Products/RemoveItemConfirmPopup.cs
> +			ConfirmButton.WaitElementAppears();
Same thing: it's better to put waits as separate step. Here you just initialize elements

2018-01-24 09:55 UTC, etolmachev commented on OvernightPrintsSpecBindings/TestBase/Pages/Products/RemoveItemConfirmPopup.cs
> +		public string GetHeader()
Should be GetHeaderText. Current name points to getting element itself, but not getting text

2018-02-01 12:34 UTC, merged